//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public long usuarioUID { get; set; }
        public string cpf { get; set; }
        public string senha { get; set; }
        public string senhaSecundaria { get; set; }
        public string email { get; set; }
        public bool ativo { get; set; }
        public System.DateTime dataCriacao { get; set; }
    }
}
